name: "[Dispatch] Create Plugin Template"

on:
  workflow_dispatch:
    inputs:
      dest:
        description: 'target repository ({repository_name})'
        required: true
      resource_type:
        description: 'plugin type ex) (inventory.Collector, cost-analysis.DataSource, monitoring.Webhook, notification.Notification ...)'
        required: true
        default: 'inventory.Collector'
      core-version:
        description: 'core version'
        required: true
        default: '2.0'

jobs:
  owner_check:
    if: github.repository_owner == 'forest-extension'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}

  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set git user
        run: git config --global user.email admin@forest-extension

      - name: set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: install requirements
        run: pip install --upgrade -r pkg/pip_requirements.txt

      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV

      - name: git clone dest repository
        run: |
          git clone https://github.com/forest-extension/${{ github.event.inputs.dest }}.git

      - name: create template with topics
        run: |
          python src/main.py template --dest ${{  github.event.inputs.dest }} --resource-type ${{ github.event.inputs.resource_type }} --core-version ${{ github.event.inputs.core-version }}

      - name: extract service from resource type to lower case
        run: |
          echo "SERVICE=$(echo ${{ github.event.inputs.resource_type }} | cut -d '.' -f1 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: install spaceone package
        run: |
          pip install --upgrade spaceone-core
          pip install --upgrade --pre spaceone-$SERVICE

      - name: Use Environment Variable
        # Replace '-' with '_' in the SERVICE environment variable
        run: echo "SERVICE=${SERVICE//-/_}" >> $GITHUB_ENV

      - name: create plugin template
        run: |
          spaceone create-project -s spaceone.$SERVICE.plugin.collector.skeleton ${{ github.event.inputs.dest }}/src/plugin

      - name: push changes
        run: |
          cd ${{ github.event.inputs.dest }}
          git config user.name github-actions
          git config user.email admin@forest-extension
          git add .
          git commit -m "[CI] Create plugin template"
          git push origin master